# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3f34e0360ea40c983c3d6de1e79bfd89274247e30d24ea132a0ab442d8f49760c8012b858a9557b3e4dc2330abf1a98571470f260075deb9679b36123454558

test:
  secret_key_base: 2c5cd8b8ee0160d63a94ab2b06030df5487fedc7c49ec69a33d606ddb6cf3f74f87a1e1dd8f5ab039923a3a754fd2d8e86f7ae3cbfd61112f86c135311d4c22f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
