if count = Product.count > 0
  Product.delete_all
  puts "Deleting #{count} old rows of seed data"
end
Product.create!([
  {title: "Alice in Wonderland", description: "Young Alice is sitting by the river bank with her older sister,\n    feeling bored; her sister's book has no pictures or conversation, and thus holds no interest for Alice. Suddenly,\n    a white rabbit scampers back, proclaims that it is very late, and pulls a pocket watch out of its waistcoat. Though\n    she initially does not notice the strangeness of a talking rabbit, when she sees the rabbit's clothes and watch, she\n    becomes very interested. She follows the rabbit, hopping right down a deep rabbit hole after him, giving no thought\n    of how she plans to get out again.", picture: "alice-in-wonderland.jpg", price: "7.5", date_published: "1901-01-01"},
  {title: "The Adventures of Sherlock Holmes", description: "A collection of 12 Sherlock Holmes short stories,\n    originally published as single stories in the Strand Magazine from July 1891 to June 1892. The book was published in\n    England on 14 October 1892 by George Newnes Ltd and in a US Edition on 15 October by Harper. The initial combined\n    print run was 14,500 copies.", picture: "holmes.jpg", price: "12.25", date_published: "1901-01-01"},
  {title: "Pride and Prejudice", description: "Set in the English countryside in a county roughly thirty miles from\n    London, the novel opens with the Bennet family in Longbourn and their five unmarried daughters. The family itself is not\n    nearly as rich as those they interact with and because they have no sons, the property is entailed to pass to a male heir,\n    in this case Mr. Collins. Mrs. Bennet is intent on seeing her daughters married off to wealthy men and when Charles Bingley\n    arrives at nearby Netherfield Park she is excited by the prospect of introducing her daughters to him. She immediately\n    sends her husband to visit him on the first day he arrives.", picture: "pride-and-prejudice.jpg", price: "3.5", date_published: "1901-01-01"},
  {title: "The Hobbit", description: "Bilbo Baggins lives his calm and peaceful life in a comfortable hole, near\n    the bustling hobbit village of Hobbiton, smoking a pipe, drinking good beer and looking for a meal. His life style and\n    interests are typical for hobbits - small and chubby people about half the size of humans who usually dress in bright\n    colors and wear no shoes, because their large feet grow thick brown hair, and feel great love to good food and drink.\n    In the beginning of the story Bilbo has a very weak character; his main features are shyness and fear susceptibility.\n    Like most of his kind, he is fond of gardening and doesn't wish any excitement or adventure.", picture: "hobbit.jpg", price: "3.5", date_published: "2004-10-19"},
  {title: "Space Odessey 2001", description: "A story of evolution. Sometime in the\n    distant past, someone or something nudged evolution by placing a monolith on Earth (presumably elsewhere\n    throughout the universe as well). Evolution then enabled humankind to reach the moon's surface, where\n    yet another monolith is found, one that signals the monolith placers that humankind has evolved that far.\n    Now a race begins between computers (HAL) and human (Bowman) to reach the monolith placers. The\n    winner will achieve the next step in evolution, whatever that may be.", picture: "2001-space-odessey.jpg", price: "11.5", date_published: "1968-01-01"},
  {title: "Asimov Series", description: "Foundation is the first novel in Isaac Asimov's\n    Foundation Trilogy (later expanded into The Foundation Series). Foundation is a collection of five short\n    stories, which were first published together as a book by Gnome Press. Set in the year 0 F.E., The\n    Psychohistorians opens on Trantor, the capital of the 12,000-year-old Galactic Empire. Though the\n    empire appears stable and powerful, it is slowly decaying in ways that parallel the decline of the\n    Western Roman Empire. Hari Seldon, a mathematician and psychologist, has developed psychohistory,\n    a new field of science and psychology that equates all possibilities in large societies to mathematics,\n    allowing for the prediction of future events.", picture: "asimov-series.jpg", price: "15.3", date_published: "1951-01-01"},
  {title: "Brave New World", description: "The novel opens in the Central London\n    Hatchery and Conditioning Centre, in the years A.F., or After Ford. Ford is the God-surrogate that\n    many citizens of the World State believe is also Freud, the controversial psychosexual psychologist.\n    The Director of Hatcheries and Conditioning is leading a tour group of young students around a lab.\n    He explains the scientific process by which human beings are fertilized and custom-made, and\n    shows them the Social Predestination room, where workers create the social castes. They pass\n    onto the conditioning rooms, where they reinforce the caste divisions by sleep-teaching.", picture: "brave-new-world.jpg", price: "9.5", date_published: "1931-01-01"},
  {title: "Dracula", description: "Famous for introducing the character of the\n    vampire Count Dracula, the novel tells the story of Dracula's attempt to relocate from Transylvania\n    to England, and the battle between Dracula and a small group of men and women led by Professor\n    Abraham van Helsing.", picture: "dracula.jpg", price: "13.5", date_published: "1897-01-01"},
  {title: "Frankenstein", description: "Rescued by the sea captain, Frankenstein\n    relays events that begin as he pieces together a man using old body parts. Once he manages to\n    create the horrible life, however, Frankenstein regrets his action immediately and flees his home.\n    When he returns, he finds the monster is gone. Shortly after, Frankenstein hears that his brother\n    has been murdered. A series of tragic events follow, as the monster searches for love and Frankenstein\n    suffers the consequences of his immoral act.", picture: "frankenstien.jpg", price: "12.5", date_published: "1818-01-01"},
  {title: "Great Expectations", description: "Pip, a young orphan living with his\n    sister and her husband in the marshes of Kent, sits in a cemetery one evening looking at his\n    parents tombstones. Suddenly, an escaped convict springs up from behind a tombstone, grabs\n    Pip, and orders him to bring him food and a file for his leg irons. Pip obeys, but the fearsome\n    convict is soon captured anyway. The convict protects Pip by claiming to have stolen the items himself.", picture: "great-expectations.jpg", price: "8.99", date_published: "1860-01-01"},
  {title: "Hitch Hiker's Guide", description: "Adams's fictional Guide is an electronic\n    guidebook to the Milky Way galaxy, originally published by Megadodo Publications, one of the great\n    publishing houses of Ursa Minor Beta. The narrative of the various versions of the story are frequently\n    punctuated with excerpts from the Guide.", picture: "the-hitchhikers-guide.jpg", price: "17.5", date_published: "1978-01-01"},
  {title: "Sleeping Murder", description: "Gwenda begins to believe that she\n    must be psychic, as she seems to know things about the house which she could not possibly know:\n    the location of a connecting door that had been walled over, the pattern of a previous wallpaper, a\n    set of steps in the garden that are not where they should be, and so on. Becoming increasingly\n    uneasy, she accepts an invitation to stay for a few days in London with Miss Marple's somewhat\n    pretentious nephew Raymond West and his wife Joan (who appear also in other stories with Miss Marple).", picture: "sleeping-murder.jpg", price: "3.5", date_published: "1976-01-01"},
  {title: "The Girl With The Dragon Tattoo", description: "In December 2002, Mikael\n    Blomkvist, publisher of the Swedish political magazine Millennium, loses a libel case involving allegations\n    about billionaire industrialist Hans-Erik Wennerstrom. He is sentenced to three months in prison, and\n    ordered to pay hefty damages and costs. Soon afterwards, he is invited to meet Henrik Vanger, the retired\n    CEO of the Vanger Corporation, unaware that Vanger has checked into his personal and professional\n    history; the investigation of Blomkvist's circumstances has been carried out by Lisbeth Salander, an\n    unusual young woman who works as a surveillance agent with Milton Security; even Salander's boss,\n    Armansky, has doubts about her but is afraid to enquire too closely into her background.", picture: "girl-with-the-dragon-tattoo.jpg", price: "12.98", date_published: "2005-01-01"},
  {title: "The Hound of the Baskervilles", description: "The Hound of the Baskervilles\n    opens with a mini mystery. Sherlock Holmes and Dr. Watson speculate on the identity of the owner\n    of a cane that has been left in their office by an unknown visitor. Wowing Watson with his fabulous powers\n    of observation, Holmes predicts the appearance of James Mortimer, owner of the found object and a\n    convenient entree into the baffling curse of the Baskervilles.", picture: "hound-of-the-baskervilles.jpg", price: "7.5", date_published: "1901-01-01"},
  {title: "The Time Machine", description: "The novel's appeal lies in its attempt\n   to fathom what will become of human beings in the distant future. By making the central character\n   of his story a time traveler who can transport himself back and forth in time with the aid of a machine\n   he invented, Wells is able to explore many of the themes that obsessed him, including class\n   inequality, evolution, and the relationship between science and society.", picture: "time-machine.jpg", price: "5.75", date_published: "1894-01-01"},
  {title: "To Kill a Mocking Bird", description: "The book depicts the experiences\n    of a young girl, Scout, and her family in a Southern town. This controversial work deals with aspects\n    of racism, and involves other aspects of violence and alienation.", picture: "kill-a-mocking-bird.jpg", price: "9.5", date_published: "1960-01-01"},
  {title: "The No. 1 Ladies' Detective Agency", description: "Wayward daughters.\n  Missing Husbands. Philandering partners. Curious conmen. If you've got a problem, and no one else\n  can help you, then pay a visit to Precious Ramotswe, Botswana's only - and finest - female private\n  detective. Her methods may not be conventional, and her manner not exactly Miss Marple, but she's\n  got warmth, wit and canny intuition on her side, not to mention Mr J. L. B. Matekoni, the charming\n  proprietor of Tlokweng Road Speedy Motors. And Precious is going to need them all as she sets out\n  on the trail of a missing child, a case that tumbles our heroine into a hotbed of strange situations\n  and more than a little danger . . .", picture: "ladies-detective-agency.jpg", price: "7.99", date_published: "2004-06-05"},
  {title: "Ruby on Rails 4th Edition", description: "How to Code", picture: "ruby-on-rails.jpg", price: "30.0", date_published: "2014-10-01"}
])
